- hosts: riak_cluster
  sudo: True
  roles:
  - { role: basho.riakcs-packages, tags: ["riakcs", "packages"] }
  - { role: basho.riakcs, tags: ["riakcs"], riakcs_anon_user_creation: 'true' }

- hosts: stanchion
  sudo: True
  roles:
  - { role: basho.stanchion, tags: ["stanchion"] }

- include: form_cluster.yml
- include: utils.yml
