- hosts: riak_cluster
  sudo: True
  roles:
  - { role: basho.riakcs-packages, tags: ["riakcs", "packages"] }
  - { role: basho.riakcs, tags: ["riakcs"] }

- hosts: stanchion
  sudo: True
  roles:
  - { role: basho.stanchion, tags: ["stanchion"] }

- include: form_cluster.yml
